#!/bin/bash

case $BLOCK_BUTTON in
	1) mpc toggle &> /dev/null ;;
	3) mpc next &> /dev/null ;;
esac

 
if ! mpc status &> /dev/null; then
  echo ""
else
  ARTIST=$(mpc --format '%artist%' current)
  TITLE=$(mpc --format '%title%' current)
  STATE=$(mpc status '%state%')

  if [ "$STATE" = "paused" ]; then
    ICON=""
  else
    ICON=""
  fi

  if [ ${#ARTIST} -gt 25 ]; then
    ARTIST="${ARTIST:0:25}..."
  fi 

  if [ ${#TITLE} -gt 25 ]; then
    TITLE="${TITLE:0:25}..."
  fi 

  echo "[$ICON $ARTIST - $TITLE]"
fi

