#!/bin/bash

mpc status &> /dev/null 
if [ $? -ne 0 ]; then
  echo ""
else
  ARTIST=$(mpc --format '%artist%' current)
  TITLE=$(mpc --format '%title%' current)
  STATE=$(mpc status '%state%')

  if [ "$STATE" = "paused" ]; then
    ICON=""
  else
    ICON=""
  fi

  if [ ${#ARTIST} -ge 15 ]; then
    ARTIST="${ARTIST:0:15}..."
  fi 

  if [ ${#TITLE} -ge 15 ]; then
    TITLE="${TITLE:0:15}..."
  fi 

  echo "[$ICON $ARTIST - $TITLE]"
fi
