#!/bin/bash

R1=`cat /sys/class/net/wlan0/statistics/rx_bytes`
T1=`cat /sys/class/net/wlan0/statistics/tx_bytes`
sleep 1
R2=`cat /sys/class/net/wlan0/statistics/rx_bytes`
T2=`cat /sys/class/net/wlan0/statistics/tx_bytes`
TBPS=`expr $T2 - $T1`
RBPS=`expr $R2 - $R1`
TKBPS=`echo $TBPS | numfmt --to=iec-i`
RKBPS=`echo $RBPS | numfmt --to=iec-i`
icon=""
icon1=""

echo "[$icon1 ${TKBPS}B/s $icon ${RKBPS}B/s]"
