#!/bin/bash

case $BLOCK_BUTTON in
  1) volume.sh mute ;;
  3) pavucontrol &> /dev/null ;;
  4) volume.sh up ;;
  5) volume.sh down ;;
esac

# LEVEL=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{printf "%.0f", $2*100}')
VOL=$(wpctl get-volume @DEFAULT_AUDIO_SINK@)
[ "$VOL" != "${VOL%\[MUTED\]}" ] && echo "[󰝟 Muted]" && exit
VOL=$(echo "$VOL" | awk '{printf "%.0f", $2*100}')

if [ "$VOL" -gt 75 ]; then
  ICON=""
elif [ "$VOL" -gt 50 ]; then
  ICON="󰕾"
elif [ "$VOL" -gt 25 ]; then
  ICON="󰖀"
elif [ "$VOL" -gt 0 ]; then
  ICON="󰕿"
fi
echo "[$ICON $VOL%]"

