gui:
  theme:
    lightTheme: false
    activeBorderColor:
      - "#f6c177" # Green
      - bold
    inactiveBorderColor:
      - "#e0def4" # Text
    optionsTextColor:
      - "#c4a7e7" # Blue
    selectedLineBgColor:
      - "#1f1d2e" # Surface0
    selectedRangeBgColor:
      - "#1f1d2e" # Surface0
    cherryPickedCommitBgColor:
      - "#9ccfd8" # Teal
    cherryPickedCommitFgColor:
      - "#c4a7e7" # Blue
    unstagedChangesColor:
      - "#eb6f92" # Red
  nerdFontsVersion: "3"
git:
  overrideGpg: true
  paging:
    colorArg: always
    pager: delta --dark --paging=never
customCommands:
  # - key: 'c'
  #   description: 'create new commit using cocogitto'
  #   prompts:
  #     - type: 'menu'
  #       title: 'What kind of commit is it?'
  #       options:
  #         - name: 'feat'
  #           description: 'a new feature'
  #           value: 'feat'
  #         - name: 'fix'
  #           description: 'a bug fix'
  #           value: 'fix'
  #         - name: 'refactor'
  #           description: 'a code change that neither fixes a bug nor adds a feature'
  #           value: 'refactor'
  #         - name: 'chore'
  #           description: "other changes that don't modify src or test files"
  #           value: 'chore'
  #         - name: 'build'
  #           description:
  #             'changes that affect the build system or external dependencies
  #             (example scopes: gulp, broccoli, npm)'
  #           value: 'build'
  #         - name: 'perf'
  #           description: 'a code change that improves performance'
  #           value: 'perf'
  #         - name: 'style'
  #           description:
  #             'changes that do not affect the meaning of the code (white-space,
  #             formatting, missing semi-colons, etc)'
  #           value: 'style'
  #         - name: 'ci'
  #           description:
  #             'changes to our CI configuration files and scripts (example
  #             scopes: Travis, Circle, BrowserStack, SauceLabs)'
  #           value: 'ci'
  #         - name: 'docs'
  #           description: 'documentation only changes'
  #           value: 'docs'
  #         - name: 'test'
  #           description: 'adding missing tests or correcting existing tests'
  #           value: 'test'
  #     - type: 'input'
  #       title: 'What is the scope?'
  #       initialValue: ''
  #     - type: 'input'
  #       title: 'What is the commit message?'
  #       initialValue: ''
  #   command:
  #     cog commit {{index .PromptResponses 0}} {{index .PromptResponses 2 |
  #     quote}} {{index .PromptResponses 1}}
  #   context: 'files'
  #   loadingText: 'creating commit...'
  - key: "b"
    description: "automatically bump version and generate changelog"
    command: "cog bump --auto"
    context: "tags"
    prompts:
      - type: "confirm"
        title: "Confirm:"
        body: "Are you sure you want to automatically bump version and generate changelog?"
  - key: "P"
    context: global
    command: git push -u origin HEAD
    description: Push
    stream: true
