gui:
  theme:
    lightTheme: false
    activeBorderColor:
      - '#a6e3a1' # Green
      - bold
    inactiveBorderColor:
      - '#cdd6f4' # Text
    optionsTextColor:
      - '#89b4fa' # Blue
    selectedLineBgColor:
      - '#313244' # Surface0
    selectedRangeBgColor:
      - '#313244' # Surface0
    cherryPickedCommitBgColor:
      - '#94e2d5' # Teal
    cherryPickedCommitFgColor:
      - '#89b4fa' # Blue
    unstagedChangesColor:
      - red # Red
git:
  overrideGpg: true
customCommands:
  - key: 'c'
    description: 'create new commit using cocogitto'
    prompts:
      - type: 'menu'
        title: 'What kind of commit is it?'
        options:
          - name: 'feat'
            description: 'a new feature'
            value: 'feat'
          - name: 'fix'
            description: 'a bug fix'
            value: 'fix'
          - name: 'refactor'
            description: 'a code change that neither fixes a bug nor adds a feature'
            value: 'refactor'
          - name: 'chore'
            description: "other changes that don't modify src or test files"
            value: 'chore'
          - name: 'build'
            description:
              'changes that affect the build system or external dependencies
              (example scopes: gulp, broccoli, npm)'
            value: 'build'
          - name: 'perf'
            description: 'a code change that improves performance'
            value: 'perf'
          - name: 'style'
            description:
              'changes that do not affect the meaning of the code (white-space,
              formatting, missing semi-colons, etc)'
            value: 'style'
          - name: 'ci'
            description:
              'changes to our CI configuration files and scripts (example
              scopes: Travis, Circle, BrowserStack, SauceLabs)'
            value: 'ci'
          - name: 'docs'
            description: 'documentation only changes'
            value: 'docs'
          - name: 'test'
            description: 'adding missing tests or correcting existing tests'
            value: 'test'
      - type: 'input'
        title: 'What is the scope?'
        initialValue: ''
      - type: 'input'
        title: 'What is the commit message?'
        initialValue: ''
    command:
      cog commit {{index .PromptResponses 0}} {{index .PromptResponses 2 |
      quote}} {{index .PromptResponses 1}}
    context: 'files'
    loadingText: 'creating commit...'
  - key: 'b'
    description: 'automatically bump version and generate changelog'
    command: 'cog bump --auto'
    context: 'tags'
    prompts:
      - type: 'confirm'
        title: 'Confirm:'
        body: 'Are you sure you want to automatically bump version and generate changelog?'
