# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[manager]
cwd = { fg = "#2aa198" } # Cyan

# Hovered
hovered = { reversed = true }
preview_hovered = { underline = true }

# Find
find_keyword = { fg = "#b58900", bold = true, italic = true, underline = true } # Yellow
find_position = { fg = "#d33682", bg = "reset", bold = true, italic = true }    # Magenta

# Marker
marker_copied = { fg = "#859900", bg = "#859900" }   # Green
marker_cut = { fg = "#dc322f", bg = "#dc322f" }      # Red
marker_marked = { fg = "#b58900", bg = "#b58900" }   # Yellow
marker_selected = { fg = "#268bd2", bg = "#268bd2" } # Blue

# Tab
tab_active = { fg = "#002b36", bg = "#839496" }   # Base03, Base0
tab_inactive = { fg = "#839496", bg = "#073642" } # Base0, Base02
tab_width = 1

# Count
count_copied = { fg = "#002b36", bg = "#859900" }   # Base03, Green
count_cut = { fg = "#002b36", bg = "#dc322f" }      # Base03, Red
count_selected = { fg = "#002b36", bg = "#268bd2" } # Base03, Blue

# Border
border_symbol = "│"
border_style = { fg = "#586e75" } # Base01

# Highlighting
# syntect_theme = "~/.config/yazi/Solarized-Dark.tmTheme"

# : }}}


# : Status {{{

[status]
separator_open = ""
separator_close = ""
separator_style = { fg = "#073642", bg = "#073642" } # Base02, Base02

# Mode
mode_normal = { fg = "#002b36", bg = "#268bd2", bold = true } # Base03, Blue
mode_select = { fg = "#002b36", bg = "#859900", bold = true } # Base03, Green
mode_unset = { fg = "#002b36", bg = "#cb4b16", bold = true }  # Base03, Orange

# Progress
progress_label = { fg = "#ffffff", bold = true }
progress_normal = { fg = "#268bd2", bg = "#073642" } # Blue, Base02
progress_error = { fg = "#dc322f", bg = "#073642" }  # Red, Base02

# Permissions
permissions_t = { fg = "#268bd2" } # Blue
permissions_r = { fg = "#b58900" } # Yellow
permissions_w = { fg = "#dc322f" } # Red
permissions_x = { fg = "#859900" } # Green
permissions_s = { fg = "#586e75" } # Base01

# : }}}


# : Input {{{

[input]
border = { fg = "#268bd2" }    # Blue
title = {}
value = {}
selected = { reversed = true }

# : }}}


# : Select {{{

[select]
border = { fg = "#268bd2" } # Blue
active = { fg = "#d33682" } # Magenta
inactive = {}

# : }}}


# : Tasks {{{

[tasks]
border = { fg = "#268bd2" }    # Blue
title = {}
hovered = { underline = true }

# : }}}


# : Which {{{

[which]
mask = { bg = "#073642" }            # Base02
cand = { fg = "#2aa198" }            # Cyan
rest = { fg = "#93a1a1" }            # Base1
desc = { fg = "#d33682" }            # Magenta
separator = "  "
separator_style = { fg = "#586e75" } # Base01

# : }}}


# : Help {{{

[help]
on = { fg = "#d33682" }                     # Magenta
exec = { fg = "#2aa198" }                   # Cyan
desc = { fg = "#93a1a1" }                   # Base1
hovered = { bg = "#586e75", bold = true }   # Base01
footer = { fg = "#073642", bg = "#839496" } # Base02, Base0

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
  # Images
  { mime = "image/*", fg = "#2aa198" }, # Cyan

  # Videos
  { mime = "{audio,video}/*", fg = "#b58900" }, # Yellow

  # Archives
  { mime = "application/*zip", fg = "#d33682" },                               # Magenta
  { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#d33682" }, # Magenta

  { mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#859900" }, # Green

  # Fallback
  { name = "*", fg = "#839496" },  # Base0
  { name = "*/", fg = "#268bd2" }, # Blue
]

# : }}}
