#!/usr/bin/bash

set -euo pipefail

if [[ $# -eq 0 ]]; then
	printf "Package name? "
	read -r PACKAGE_NAME

	if [[ -z "$PACKAGE_NAME" ]]; then
		echo "Error: package name should not be empty"
		exit 1
	fi
else
	PACKAGE_NAME="$1"
fi

mapfile -d "/" PACKAGE_PARTS <<<"$PACKAGE_NAME"
DIR_NAME="${PACKAGE_PARTS[-1]%?}"

# create project directory
mkdir "$DIR_NAME"

# open the project directory
cd "$DIR_NAME"

# Initialize Git
printf "Initialize Git [Y/n]? "
read -n1 -r GIT
if [[ -z "$GIT" ]]; then
	GIT="y"
else
	echo
fi

if [[ ${GIT,,} == "y" ]]; then
	git init -q
fi

# Initialize go project
go mod init "$PACKAGE_NAME" &>/dev/null

DEPS=("github.com/gofiber/fiber/v2" "github.com/joho/godotenv" "github.com/guregu/null/v5")

# Installing validator
printf "Install go-playground/validator (Schema Validation Library) [Y/n]? "
read -n1 -r VALIDATOR
if [[ -z "$VALIDATOR" ]]; then
	VALIDATOR="y"
else
	echo
fi

if [[ ${VALIDATOR,,} == "y" ]]; then
	DEPS+=("github.com/go-playground/validator/v10" "github.com/go-playground/universal-translator" "github.com/go-playground/locales")
fi

# Installing fx
printf "Install uber/fx (Dependency Injection Framework) [Y/n]? "
read -n1 -r DI
if [[ -z "$DI" ]]; then
	DI="y"
else
	echo
fi

if [[ ${DI,,} == "y" ]]; then
	DEPS+=("go.uber.org/fx@latest")
fi

# Installing jwt
printf "Install JWT library [Y/n]? "
read -n1 -r JWT
if [[ -z "$JWT" ]]; then
	JWT="y"
else
	echo
fi

if [[ ${JWT,,} == "y" ]]; then
	DEPS+=("github.com/golang-jwt/jwt/v5" "github.com/gofiber/contrib/jwt")
fi

# Installing argon2
printf "Install argon2 (Password Hashing Library) [Y/n]? "
read -n1 -r ARGON2
if [[ -z "$ARGON2" ]]; then
	ARGON2="y"
else
	echo
fi

if [[ ${ARGON2,,} == "y" ]]; then
	DEPS+=("github.com/matthewhartstonge/argon2")
fi

# Installing db library
echo "Choose your database library:"
echo "	1. sqlx"
echo "	2. gorm"
echo "	n. none"
printf "[1/2/n] (default=n)? "
read -n1 -r DB

case $DB in
"1")
	DEPS+=("github.com/jmoiron/sqlx")
	;;
"2")
	DEPS+=("gorm.io/gorm")
	;;
esac
if [[ -n "$DB" ]]; then
	echo
fi

# Installing All Dependencies
echo "Installing dependencies..."
go get -u ${DEPS[*]} &>/dev/null

echo ".env" >.gitignore
echo "PORT=8080" >.env

if [[ ${DI,,} == "y" ]]; then
	cat <<EOF >main.go
package main

import (
	"context"
	"os"

	"github.com/gofiber/fiber/v2"
	_ "github.com/joho/godotenv/autoload"
	"go.uber.org/fx"
)

type HelloHandler struct{}

func NewHelloHandler() *HelloHandler {
	return &HelloHandler{}
}

func (*HelloHandler) Hello(c *fiber.Ctx) error {
	return c.SendString("Hello, World!")
}

func NewFiber(lc fx.Lifecycle, helloHandler *HelloHandler) *fiber.App {
	port := os.Getenv("PORT")

	app := fiber.New()

	app.Get("/", helloHandler.Hello)

	lc.Append(fx.Hook{
		OnStart: func(ctx context.Context) error {
			go func() {
				if err := app.Listen(":" + port); err != nil {
					panic(err)
				}
			}()

			return nil
		},
		OnStop: func(ctx context.Context) error {
			return app.Shutdown()
		},
	})

	return nil
}

func main() {
	fx.New(
		fx.Provide(NewHelloHandler),
		fx.Invoke(NewFiber),
	).Run()
}
EOF
else
	cat <<EOF >main.go
package main

import (
	"os"

	"github.com/gofiber/fiber/v2"
	_ "github.com/joho/godotenv/autoload"
)

var port = os.Getenv("PORT")

func main() {
    app := fiber.New()

    app.Get("/", func(c *fiber.Ctx) error {
        return c.SendString("Hello, World!")
    })

    app.Listen(":"+port)
}
EOF
fi

printf "Installation success!\n\n"
echo "Run these commands to start the app:"
echo "	cd $DIR_NAME"
echo "	go run ."
