#!/bin/env bash

# comm -12 <((checkupdates ; yay -Qua) | awk -F' ' '{print $1, $2}' | sort) <(yay -Qe | sort) | wc -l
# comm -12 <((parallel ::: 'checkupdates' 'yay -Qua') | awk -F' ' '{print $1, $2}' | sort) <(yay -Qe | sort) | wc -l
comm -12 <((checkupdates & yay -Qua & wait) | awk -F' ' '{print $1, $2}' | sort) <(yay -Qe | sort) | wc -l
