#!/usr/bin/env bash

set -euo pipefail

LIST_OF_ACTION="poweroff\nreboot"
LIST_OF_CONFIRMATION="no\nyes"

ACTION=$(printf $LIST_OF_ACTION | dmenu -fn 'JetBrainsMono Nerd Font-12' -i -p 'Power menu: ')
CONFIRMATION=$(printf $LIST_OF_CONFIRMATION | dmenu -fn 'JetBrainsMono Nerd Font-12' -i -p "Are you sure want to ${ACTION}?: ")

if [ "$CONFIRMATION" = "yes" ]; then
  eval "$ACTION"
else
  echo "Gak jadi"
fi
