#!/usr/bin/env bash

set -euo pipefail

SOUND_PACK=$(\ls $XDG_DATA_HOME/rustyvibes/soundpacks | xargs | tr ' ' '\n' | grep -v '.zip$' | dmenu -fn 'JetBrainsMono Nerd Font-13' -nb '#1e1e2e' -nf '#cdd6f4' -sb '#89dceb' -sf '#1e1e2e' -i -b -p 'Choose the sound pack: ')
SOUND_PACK_PATH="$XDG_DATA_HOME/rustyvibes/soundpacks/$SOUND_PACK"

pidof rustyvibes && killall rustyvibes
rustyvibes $SOUND_PACK_PATH & disown
