#!/usr/bin/env bash

set -euo pipefail

SOUND_PACK=$({ \ls $XDG_DATA_HOME/rustyvibes/soundpacks; printf "\nkill"; } | xargs | tr ' ' '\n' | grep -v '.zip$' | dmenu -fn 'JetBrainsMono Nerd Font-12' -nb '#1e1e2e' -nf '#cdd6f4' -sb '#084ab7' -sf '#cdd6f4' -i -p 'Rustyvibes: ')

pidof rustyvibes && killall rustyvibes

if [ "$SOUND_PACK" = "kill" ]; then
  notify-send -i stop "Rustyvibes has been killed" "Bye bye..."
  exit 0
fi

SOUND_PACK_PATH="$XDG_DATA_HOME/rustyvibes/soundpacks/$SOUND_PACK"

rustyvibes -v 75 $SOUND_PACK_PATH & disown
notify-send -i checkmark "Rustyvibes has been activated" "Using $SOUND_PACK soundpack"
