#!/usr/bin/env bash

set -euo pipefail

SOUND_PACK=$({ \ls $XDG_DATA_HOME/rustyvibes/soundpacks; echo -e "\nkill"; } | xargs | tr ' ' '\n' | grep -v '.zip$' | dmenu -fn 'JetBrainsMono Nerd Font-13' -nb '#1e1e2e' -nf '#cdd6f4' -sb '#89dceb' -sf '#1e1e2e' -i -b -p 'Rustyvibes: ')

if [ "$SOUND_PACK" == "kill" ]; then
  pidof rustyvibes && killall rustyvibes
  notify-send -i stop "Rustyvibes has been killed" "Bye bye..."
  exit 0
fi

SOUND_PACK_PATH="$XDG_DATA_HOME/rustyvibes/soundpacks/$SOUND_PACK"

rustyvibes $SOUND_PACK_PATH & disown
notify-send -i checkmark "Rustyvibes has been activated" "Using $SOUND_PACK soundpack"
