#!/bin/sh

NOCOLOR='\033[0m'
GREEN='\033[0;32m'

print_log() {
  TIMESTAMP="${GREEN}[$(date --rfc-3339=s)]${NOCOLOR} "
  echo -e $TIMESTAMP $1
}

handle_error() {
  print_log $1
  exit 1
}

# backup
print_log "Backing up system with Timeshift..."
sudo timeshift --create || handle_error "Failed to backup system"

# system upgrade
print_log "Updating database and upgrading system..." 
paru || handle_error "Failed to upgrading system"

# updating pkgfile
print_log "Updating pkgfile..."
sudo pkgfile -u || handle_error "Failed to updating pkgfile"

# backup packages name
print_log "Backing up packages list..."
paru -Qqe > $HOME/.dotfiles/pkglist.txt || handle_error "Failed to backup packages name"

# clean trash
print_log "Cleaning up trashes..."
trash-empty 30 || handle_error "Failed to clean trashes"

# done
print_log "Update is done, please reboot the system"
