#!/usr/bin/env bash

set -euo pipefail

NOCOLOR='\033[0m'
GREEN='\033[0;32m'

get_timestamp() {
	echo "${GREEN}[$(date --rfc-3339=s)]${NOCOLOR} "
}

print_log() {
	TIMESTAMP=$(get_timestamp)
	printf "$TIMESTAMP %s\n" "$1"
}

# handle_error() {
#   print_log $1
#   exit 1
# }

# backup
print_log "Backing up system with Timeshift..."
sudo-rs timeshift --create
OLDEST_BACKUP=$(sudo-rs timeshift --list | rg '0    >  ' | xargs | cut -d ' ' -f 3)
sudo-rs timeshift --delete --snapshot "${OLDEST_BACKUP}"

# backup packages name
print_log "Backing up packages list..."
yay -Qqe >"$HOME/.dotfiles/pkglist.txt"

# clean trash
print_log "Cleaning up trashes..."
trash-empty 7

# system upgrade
print_log "Updating database and upgrading system..."
yay -Syyu

# updating pkgfile
# print_log "Updating pkgfile..."
# sudo-rs pkgfile -u

# done
print_log "Update is done, please reboot the system"
