#!/usr/bin/env bash

# watch-yt - simple bash script to search and watch youtube video from terminal
#
# Dependencies:
# - yt-dlp
# - mpv
# - fzf

set -euo pipefail

QUERY="$1"

if printf '%s\n' "$QUERY" | grep -Eq '^(https?://)?(www\.youtube\.com|youtu\.be)/.+$'; then
  # echo "$QUERY is a valid URL"
  VIDEO_URL="$QUERY"
else
  # echo "$QUERY is not a valid URL"
  YOUTUBE_ID=$(yt-dlp ytsearch5:"$QUERY" --print 'channel' --print 'title' --print 'id' | while read line1; do read line2; read line3; echo -e "$line1~$line2~$line3"; done | column -t -s '~' | fzf | awk '{print $NF}')
  VIDEO_URL="https://youtu.be/$YOUTUBE_ID"
fi

VIDEO_ID=$(yt-dlp -F "$VIDEO_URL" | sed '/ID/,$!d' | grep -v 'mhtml' | grep -v 'audio only' | fzf --tac | awk '{print $1}')
AUDIO_ID="bestaudio"

echo "Video is loading, please wait..."

mpv --ytdl-format="${VIDEO_ID}+${AUDIO_ID}/best" --no-terminal $VIDEO_URL & disown
